name: project running

on:
  push:
    branches:
      -main

jobs:
  docker_running:
    name: run via docker
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: run docker compose
        run : |
          cd /project
          docker compose up
          sleep 10 # Wait for the server to start
          curl --fail http://localhost:8000 # Test the app
