name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        working-directory: ./project
        # working-directory: "/home/dhaider/Documents/fast api project/FastApiPro/project"
        run: |
          echo "Building Docker Image..."
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/fastapi-ci-cd-app:latest .
        # cd .. && cd "/project" && docker build -t fastapi-ci-cd-app:latest .

  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Set up Python Environment
  #       working-directory: ./project
  #       run: |
  #         echo "Setting up virtual environment..."
  #         python3 -m venv venv
  #         source venv/bin/activate
  #         pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Run Tests
  #       working-directory: ./project
  #       run: |
  #         echo "Running tests..."
  #         venv/bin/pytest --rootdir=./
  #       # venv/bin/pytest /tests/test_fastapi.py

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Stop Existing Container
        working-directory: ./project
        run: |
          echo "Stopping and removing any existing container..."
          docker rm -f fastapi-app-container || true

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy Application
        working-directory: ./project
        run: |
          echo "Deploying Application..."
          docker run -d --name fastapi-app-container -p 8000:8000 "${{ secrets.DOCKER_USERNAME }}"/fastapi-ci-cd-app:latest
          echo "Application deployed successfully and is running on http://localhost:8000"
